package main

import "strings"

// Method template for generating accessors.
const methodTemplate = `// Code generated by accessor generator. DO NOT EDIT.

package {{.PackageName}}

{{if .Imports}}import (
{{range .Imports}}
	{{.}}
{{end}}
)
{{end}}

{{range $struct := .Structs}}
{{range .Fields}}
{{if eq $.Mode "getter" "accessor"}}
{{if .PrimitivePointer}}
func (s *{{$struct.StructName}}) Get{{ CapitalizeFirstLetter .Name}}() (zero {{.DeferrencedFieldType}}) {
	if s == nil {
		return zero
	}
	return *s.{{.Name}}
}
{{else}}
func (s *{{$struct.StructName}}) Get{{ CapitalizeFirstLetter .Name}}() (zero {{.Type}}) {
	if s == nil {
		return zero
	}
	return s.{{.Name}}
}
{{end}}
{{end}}
{{if eq $.Mode "setter" "accessor"}}
func (s *{{$struct.StructName}}) Set{{ CapitalizeFirstLetter .Name}}(val {{.Type}}) {
	s.{{.Name}} = val
}
{{end}}
{{end}}
{{end}}
`

func CapitalizeFirstLetter(s string) string {
	return strings.ToUpper(s[:1]) + s[1:]
}
